In [1]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv('results/LED_result.csv')
df.head()

,Unnamed: 0,dataset,ensemble,base_naive,base_hatt,base_MLP,feature_selector,avg_selected_features,final_naive,final_hatt,final_MLP,random_ensemble,total_samples,accuracy,running_time
0,0,data/LED.csv,awe,1,0,0,0,0.000,0,0,0,0,25000,0.7286,463.46
1,1,data/LED.csv,aee,1,0,0,0,0.000,0,0,0,0,25000,0.7334,579.26
2,2,data/LED.csv,heft,1,1,0,FCBF,15.208,10,0,0,0,25000,0.6547,265.37
3,3,data/LED.csv,heft,1,0,1,FCBF,15.208,10,0,0,0,25000,0.6563,259.44
4,4,data/LED.csv,heft,0,1,1,FCBF,15.208,0,0,10,0,25000,0.1551,54.75

In [43]:
df.sort_values(by='accuracy', ascending=False).head(40)

,Unnamed: 0,dataset,ensemble,base_naive,base_hatt,base_MLP,feature_selector,avg_selected_features,final_naive,final_hatt,final_MLP,random_ensemble,total_samples,accuracy,running_time
1,1,data/LED.csv,aee,1,0,0,0,0.000,0,0,0,0,25000,0.7334,579.26
11,11,data/LED.csv,heft,1,0,1,CMIM,25.000,1,0,1,0,25000,0.7332,99.16
15,15,data/LED.csv,heft,1,0,1,CMIM,25.000,1,0,1,1,25000,0.7311,86.16
17,17,data/LED.csv,heft,1,1,1,CMIM,25.000,1,1,1,1,25000,0.7291,5000.51
0,0,data/LED.csv,awe,1,0,0,0,0.000,0,0,0,0,25000,0.7286,463.46
13,13,data/LED.csv,heft,1,1,1,CMIM,25.000,1,1,1,0,25000,0.7283,4327.18
10,10,data/LED.csv,heft,1,1,0,CMIM,25.000,1,1,0,0,25000,0.7279,3687.44
14,14,data/LED.csv,heft,1,1,0,CMIM,25.000,1,1,0,1,25000,0.7276,3936.97
16,16,data/LED.csv,heft,0,1,1,CMIM,25.000,0,1,1,1,25000,0.6983,3940.34
12,12,data/LED.csv,heft,0,1,1,CMIM,25.000,0,1,1,0,25000,0.6895,3663.89
3,3,data/LED.csv,heft,1,0,1,FCBF,15.208,10,0,0,0,25000,0.6563,259.44
2,2,data/LED.csv,heft,1,1,0,FCBF,15.208,10,0,0,0,25000,0.6547,265.37
6,6,data/LED.csv,heft,1,1,0,FCBF,15.208,6,4,0,1,25000,0.6532,274.36
5,5,data/LED.csv,heft,1,1,1,FCBF,15.208,0,10,0,0,25000,0.6452,272.56
7,7,data/LED.csv,heft,1,0,1,FCBF,15.208,5,0,5,1,25000,0.6449,199.04
9,9,data/LED.csv,heft,1,1,1,FCBF,15.208,7,2,1,1,25000,0.6420,218.60
8,8,data/LED.csv,heft,0,1,1,FCBF,15.208,0,7,3,1,25000,0.6138,191.90
4,4,data/LED.csv,heft,0,1,1,FCBF,15.208,0,0,10,0,25000,0.1551,54.75

In [45]:
df[df.ensemble=='heft'].sort_values(by='accuracy', ascending=False)

,Unnamed: 0,dataset,ensemble,base_naive,base_hatt,base_MLP,feature_selector,avg_selected_features,final_naive,final_hatt,final_MLP,random_ensemble,total_samples,accuracy,running_time
11,11,data/LED.csv,heft,1,0,1,CMIM,25.000,1,0,1,0,25000,0.7332,99.16
15,15,data/LED.csv,heft,1,0,1,CMIM,25.000,1,0,1,1,25000,0.7311,86.16
17,17,data/LED.csv,heft,1,1,1,CMIM,25.000,1,1,1,1,25000,0.7291,5000.51
13,13,data/LED.csv,heft,1,1,1,CMIM,25.000,1,1,1,0,25000,0.7283,4327.18
10,10,data/LED.csv,heft,1,1,0,CMIM,25.000,1,1,0,0,25000,0.7279,3687.44
14,14,data/LED.csv,heft,1,1,0,CMIM,25.000,1,1,0,1,25000,0.7276,3936.97
16,16,data/LED.csv,heft,0,1,1,CMIM,25.000,0,1,1,1,25000,0.6983,3940.34
12,12,data/LED.csv,heft,0,1,1,CMIM,25.000,0,1,1,0,25000,0.6895,3663.89
3,3,data/LED.csv,heft,1,0,1,FCBF,15.208,10,0,0,0,25000,0.6563,259.44
2,2,data/LED.csv,heft,1,1,0,FCBF,15.208,10,0,0,0,25000,0.6547,265.37
6,6,data/LED.csv,heft,1,1,0,FCBF,15.208,6,4,0,1,25000,0.6532,274.36
5,5,data/LED.csv,heft,1,1,1,FCBF,15.208,0,10,0,0,25000,0.6452,272.56
7,7,data/LED.csv,heft,1,0,1,FCBF,15.208,5,0,5,1,25000,0.6449,199.04
9,9,data/LED.csv,heft,1,1,1,FCBF,15.208,7,2,1,1,25000,0.6420,218.60
8,8,data/LED.csv,heft,0,1,1,FCBF,15.208,0,7,3,1,25000,0.6138,191.90
4,4,data/LED.csv,heft,0,1,1,FCBF,15.208,0,0,10,0,25000,0.1551,54.75

In [46]:
df2 = df[df.ensemble=='heft']
df2 = df2[df2.random_ensemble==0]
print(df2['accuracy'].mean(), df2['running_time'].mean())

0.623775 1578.7237499999999

In [47]:
df2 = df[df.ensemble=='heft']
df2 = df2[df2.random_ensemble==1]
print(df2['accuracy'].mean(), df2['running_time'].mean())

0.6799999999999999 1730.985

In [48]:
df2 = df[df.ensemble=='heft']
df2 = df2[df2.feature_selector=='FCBF']
print(df2['accuracy'].mean(), df2['running_time'].mean())

0.5831500000000001 217.0025

In [49]:
df2 = df[df.ensemble=='heft']
df2 = df2[df2.feature_selector=='CMIM']
print(df2['accuracy'].mean(), df2['running_time'].mean())

0.7206249999999998 3092.70625